run:
  skip-dirs:
    - tests

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    check-shadowing: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/behzadsh/otter)
      - blank
      - dot
  gocyclo:
    min-complexity: 20
  godot:
    capital: true
  gofumpt:
    extra-rules: true
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: line-length-limit
        arguments: [ 180 ]
      - name: package-comments
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: function-length
        disabled: true
      - name: file-header
        disabled: true
      - name: nested-structs
        disabled: true
      - name: unhandled-error
        arguments:
          - "fmt.Printf"
          - "fmt.Println"
          - "fmt.Print"
  misspell:
    locale: US
    ignore-words:
      - ponisha
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errname
    - gci
    - gocyclo
    - godot
    - gofumpt
    - gosec
    - revive
    - misspell
    - prealloc
    - unconvert
    - nolintlint

issues:
  exclude:
    - "Unhandled error in call to function ([a-z][a-zA-Z0-9]+).WriteString"
    - "Unhandled error in call to function ([a-z][a-zA-Z0-9]+).WriteByte"
  exclude-rules:
    - path: cmd/indexer/commands
      text: "line is \\d+ characters, out of limit 180"
